---
namespace: demo
name: zero_trust
version: 1.0.0
readme: README.md
authors:
  - Zachary LeBlanc
description: Zero-trust infrastructure automation
license:
  - GPL-3.0-or-later
tags:
  - vault
  - zerotrust
  - security
dependencies: {}
repository: https://github.com/zacharyleblanc/ansible-zero-trust
issues: https://github.com/zacharyleblanc/ansible-zero-trust/issues
build_ignore: []
