---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "yes"
      - "no"
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

ignore: |
  .ansible/
  .venv/
  collections/
