---
galaxy_info:
  role_name: cloudflare_hostname
  author: Zachary LeBlanc
  description: >-
    Configure Cloudflare Tunnel public hostnames (ingress) and their DNS
    CNAME records
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - cloudflare
    - tunnel
    - dns
    - zerotrust
    - security
dependencies: []
