---
- name: Vault Automation
  hosts: "{{ _hosts | default('vault') }}"

  vars:
    vault_install_type: podman # podman (default) | rpm | k8s

    _vault_install_tasks:
      podman:
        - configure_host
        - install_podman
        - init_vault
      rpm:
        - configure_host
        - install_rpm
        - init_vault
      # Dev mode (default) is already initialized
      k8s: "{{ ['install_k8s'] + (vault_k8s_dev_mode) | ternary([], ['init_vault'])) }}"

    _vault_post_install_tasks:
      - configure_jwt_auth
      - configure_kv_engine
      - configure_userpass_auth

    vault_tasks: "{{ _vault_install_tasks[vault_install_type] + _vault_post_install_tasks }}"

  tasks:
    - name: Assert supported vault install type
      ansible.builtin.assert:
        fail_msg: >-
          vault_install_type must be one of: {{ _vault_install_tasks.keys() | list }}
          (got '{{ vault_install_type }}').
        that:
          - vault_install_type in _vault_install_tasks

    - name: "Run demo.zero_trust.vault"
      loop: "{{ vault_tasks }}"
      loop_control:
        loop_var: function
        label: "{{ function }}"
      ansible.builtin.include_role:
        name: demo.zero_trust.vault
        tasks_from: "{{ function }}"
