---
- name: Vault Automation
  hosts: "{{ _hosts | default('vault') }}"

  vars:
    vault_tasks:
      - configure_host
      - install_podman
      - init_vault
      - configure_jwt_auth
      - configure_kv_engine
      - configure_userpass_auth

  tasks:
    - name: "Run demo.zero_trust.vault"
      loop: "{{ vault_tasks }}"
      loop_control:
        loop_var: function
      ansible.builtin.include_role:
        name: demo.zero_trust.vault
        tasks_from: "{{ function }}"
