---
- name: Vault Automation
  hosts: "{{ _hosts | default(omit) }}"

  vars:
    vault_tasks:
      - configure_host
      - install_podman
      - init_vault

  tasks:
    - name: "Run demo.zero_trust.vault | {{ action }}"
      loop: "{{ vault_tasks }}"
      loop_control:
        loop_var: action
      ansible.builtin.include_role:
        name: demo.zero_trust.vault
        tasks_from: "{{ action }}"
